name: Peerax
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#34a4dc'
    - '#34a5db'
    - '#3399cc'
    - '#279dd8'
    - '#31a4db'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.4742057230323553
  rhythmicContrast: 0.1652862390037626
purpose: []
