name: Peerax
favicon: null
layout_spectrum: 0.673503102036193
typography_spectrum: 0.732491921633482
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8479981226846576
  lightness: 0.5610138673800975
  saturation: 0.4742057230323553
  rhythmicContrast: 0.1652862390037626
purpose: []
